= Mining Payouts With Channel Construction Using FROST Federation
:page-layout: page
:page-title: Mining Payouts With Channel Construction Using FROST Federation
:page-nav_order: 5


In a previous post I described a
link:./2024-07-04-frost-federation[federation based on FROST threshold
signatures] and a point to point communication channel. In this post,
I describe a payout mechanism based on
https://bitcointalk.org/index.php?topic=2135429.0[Belcher's
construction].

We replace a centralised hub used by Belcher with the FROST
Federation. I show that the coinbase reward is distributed and how
miners and federation members can join and leave the federation. I
also show that the federation can't deny payments to a miner without
shutting down the entire pool.

== Terminology

*Federation Member*:: A node that has locked in some bitcoin into the
"Federation Funding Transaction" as input for miner payouts. The
federation members are also responsible for other things like running
stratum servers, generating block templates and replicating miner PoW
shares among all the federation members.

*Federation*:: A collection of "Federation Members" connected directly
to each other in a point to point communication model.

*Federation Threshold Signature*:: Threshold signature generated
  together by the federation member. The threshold number of members
  required is configurable.

*Federation Public Key*:: A public key generated cooperatively by
  federation members using a Distributed Key Generation (DKG)
  protocol.

*Member Funding Transaction*:: A P2WPKH transaction, where inputs are
  UTXOs owned by a "Federation Member" and output is owned by
  Federation Public Key.

*Member Refund Transaction*:: A P2WPKH transaction, where the input is a
  Member Funding Transaction and the ouput is a Federation Member
  public key.
  
*Payout Update Transaction*:: A transaction capturing the payout made
  sent from federation to miners. There are multiple versions of this
  transaction and this is how miners balances are updated. Miners can
  spend their output at anytime without requiring a permission from
  the Federation.

  
NOTE: The member utxo to federation transaction needs some more
thinking.We need the member to be able to spend their utxo if the
federation is not able 1) use the funds in time or 2) the federation
fails and isn't able to sign any requests from member to end
membership.

Federation Threshold Signature

Miner Funding/Balance Transaction

Miner Refund Transaction

== Joining a FROST Federation as a Member

== Leaving a FROST Federation as a Member

== Miner Registraion with a Federation Member

- register using web ui
- federatiom member replicates the credentials
- miner's web ui connects to all federation members to validate credentials are replicated to all
- miner can choose to use the stratum urls for any of the members

== Federation and Miner Create Fund and Refund transactions

- Each member, pools their fund into a federation funding transaction
  that requires the federation threshold signature
- Only after enough shares have been generated by the miner.
- Miner can spend this funding transaction at any point.
- Miner has to spend this transaction within a month from when it was
  created. After that the federation will reclaim the funds.

== Coinbase Construction By Federation Member

- includes payouts for all blocks that have matured
- 
